# PERMISSIONS
SYSTEM_RUNNER: on
MAXIMUM_ROUND_COUNTER_CONFIG: 3
# SYSTEM DELAYS
SYSTEM_SMALL_DELAY_IN_SECONDS: 2
SYSTEM_MEDIUM_DELAY_IN_SECONDS: 5
SYSTEM_LARGE_DELAY_IN_SECONDS: 30
SYSTEM_XXL_DELAY_IN_SECONDS: 210
# FLOW HISTORY
START_DATE_AND_TIME: 2024-06-10 15:30:00
START_BNB_METAMASK_BALANCE: 0.03424
START_USDT_METAMASK_BALANCE: 17.561
END_BNB_METAMASK_BALANCE: 0.06008222
END_USDT_METAMASK_BALANCE: 144.12
END_DATE_AND_TIME: 2024-06-10 15:30:00
# USER DASHBOARD
ALL_ROUNDS_COUNTER: 4
PERCENT_CHANGE: 15%
YOUR_PROFIT_IN_USDT: 126.562
HOW_LONG_WAS_ON: 1 Day, 2 Hours, 30 Minutes, 15 Seconds




