# ##################################
# enable only what you need to run
# ##################################
RUNNER_WINDOWS_CONFIG: off
RUNNER_BROWSER_CONFIG: off
RUNNER_METAMASK_CONFIG: off
RUNNER_ORDER_RELOAD_CONFIG: off
RUNNER_BALANCE_RELOAD_CONFIG: off
# ##################################
# when you set what "on", run the setup
# python setup.py
# ##################################
# SYSTEM SETTINGS
# LONG | SHORT | BOTH
STRATEGY_TYPE: LONG
STRATEGY_GO_WITH_FLOW: DISABLE
# USER SETTINGS
STEP_AMOUNT_IN_BNB: 0.002
MAXIMUM_ROUND_COUNTER_CONFIG: 5
# FLOW HISTORY
ALL_ROUNDS_COUNTER: 52
PERCENT_CHANGE: 15%
YOUR_PROFIT_IN_USDT: 126.562
HOW_LONG_WAS_ON: 1 Day, 2 Hours, 30 Minutes, 15 Seconds
START_DATE_AND_TIME: 2024-06-10 15:30:000.002
START_BNB_METAMASK_BALANCE: 0.03424
START_USDT_METAMASK_BALANCE: 17.561
END_BNB_METAMASK_BALANCE: 0.00000000
END_USDT_METAMASK_BALANCE: 144.12
END_DATE_AND_TIME: 2024-06-10 15:30:00





