# CLICK CONFIG
PIXEL_CONFIG: 546,568,monitor=1
# SYSTEM DELAYS
SYSTEM_SMALL_DELAY_IN_SECONDS: 3
SYSTEM_MEDIUM_DELAY_IN_SECONDS: 6
SYSTEM_LARGE_DELAY_IN_SECONDS: 30
SYSTEM_XXL_DELAY_IN_SECONDS: 210

# RELOAD ORDER FLOW #
CANDLE_TIME: 03:14
CHECK_IF_CANDLE_TIME_IS_3: true
CLICK_CANDLE_COLOR: 295,482,monitor=1
CANDLE_COLOR: GREEN
CLICK_ENTER_UP: 698,485,monitor=1
CLICK_ENTER_DOWN: 693,522,monitor=1
CLICK_INSIDE_SET_POSITION: 743,437,monitor=1
INSERT_AMMOUNT_IN_BNB: 0.001
CLICK_ON_PANCAKE_CONFIRM_BUTTON: 696,575,monitor=1
CLICK_ON_METAMASK_CONFIRM_BUTTON: 871,562,monitor=1
CLICK_ON_CLOSE_METAMASK: 726,565,monitor=1

# RELOAD ALL FLOW #
# CHECK_IF_NEED_TO_CLOSE_PROMO_POPUP
MAXIMUM_ROUND_COUNTER: 1
CHECK_IF_NEED_TO_CLOSE_PROMO_POPUP: 984,564,monitor=1
CLOSE_THE_PROMO_POPUP: WRONG_PIXEL
# CHECK_IF_NEED_TO_COLLECT_WINNINGS
CLICK_OPEN_HISTORY_SIDEBAR: 987,275,monitor=1
CLICK_FILTER_BY_UNCOLLECTED: 883,323,monitor=1
CLICK_WINNINGS_COLOR: 917,479,monitor=1
WININGS_COLOR: WRONG_PIXEL
# COLLECT_WINNINGS
CLICK_COLLECT_WINNINGS: 917,479,monitor=1
CLICK_COLLECT_ALL_CONFIRM: 546,568,monitor=1
CLICK_CONFIRM_METAMASK_ORDER: 871,562,monitor=1
CLICK_FINISH_AND_CLOSE_METAMASK: 726,565,monitor=1
# REFRESH_BROWSER
CLICK_REFRESH_BROWSER: 92,63,monitor=1

# LOGIN FLOW # NO NEED
click_metamask_icon: 3313,133,monitor=1
# insert_metamask_password
click_unlock_metamask: 2381,387,monitor=2
# click_REFRESH_BROWSER
# SYSTEM_MEDIUM_DELAY_IN_SECONDS
click_pancake_log_in_button: 2047,587,monitor=2
click_choose_metamask_wallet: 645,533,monitor=2
click_choose_network: 2155,604,monitor=2
click_metamask_connect_button: 1659,957,monitor=2
# click_REFRESH_BROWSER
# SYSTEM_MEDIUM_DELAY_IN_SECONDS
